### ISSUE TITLE
📚  API DesignDoc: "DirectoryBucket"

### ISSUE THREAD

**Issue by Nicoretti** [exasol/bucketfs-python#103]
## Summary
Write an API specification for a **_"DirectoryBucket"_** (type name to be defined) for the `bucketfs` library. 
The `DirectoryBucket` acts as a wrapper around a `Bucket`, targeted at a specific subdirectory, to facilitate object storage operations within that subdirectory context.

### Goals
- **Simplify Path Management**: Enable components to operate in isolated subdirectories without manual path tracking.
- **Enhance Error Handling**: Reduce errors stemming from manual path management

### Functionality
- `read(path: string)`: Read the contents of a file located at `path` within the subdirectory.
- `write(path: string, content: any)`: Write `content` to a file located at `path` within the subdirectory.
- `delete(path: string)`: Delete a file or directory located at `path` within the subdirectory.
- `files()`: List all files in the current subdirectory.
- `directories()`: List all direct subdirectories as `DirectoryBucket` instances.
- `join_path(*paths: string[])`: Safely join multiple path segments, ensuring proper navigation within the subdirectory.

Note: Consider having the path operations in a path object which will/can be used by the `DirectoryBucket`.

## Related Issues
- [Issue #68 on GitHub](https://github.com/exasol/bucketfs-python/issues/68)

**Comment by tkilias** [comment]
in the bucket we used upload and download instead of write and read

https://github.com/exasol/bucketfs-python/blob/a53a7966e335274f91b7994e1d3e4c034fcefd55/exasol/bucketfs/__init__.py#L242
https://github.com/exasol/bucketfs-python/blob/a53a7966e335274f91b7994e1d3e4c034fcefd55/exasol/bucketfs/__init__.py#L278

**Comment by tkilias** [comment]
But, we also need a way to get the path of the bucket in the UDF File system for the transformer-extension..
