### ISSUE TITLE
Investigate ambiguous paths in BucketFS

### ISSUE THREAD

**Issue by ckunki** [exasol/bucketfs-python#106]
Java lib contains a test case for a path in BucketFS being a folder as well as a file at the same time.

See [tests in bucketfs-java](https://github.com/exasol/bucketfs-java/blob/76999372f5e89eb7eba23ae06c5d9416d9f38085/src/test/java/com/exasol/bucketfs/ReadEnabledBucketTest.java#L95) that should cover all possible situations.

See explanation in [bucketfs-client User guide](https://github.com/exasol/bucketfs-client/blob/main/doc/user_guide/user_guide.md#ambigue-entries-in-bucketfs)

**Comment by Nicoretti** [comment]
@ckunki I don't really get what this issue is supposed to address/investigate?
Can you elaborate and/or refine the description?
