### ISSUE TITLE
Make BucketLike.upload() return a BucketPath object

### ISSUE THREAD

**Issue by ckunki** [exasol/bucketfs-python#161]
Currenty users need to use one of the approaches described below ([Current Options](#current-options)).

Use case:
1. Upload file (or archive) to BucketFS
2. Get `udf_path` of the uploaded file

See also [BucketPath](https://github.com/exasol/bucketfs-python/blob/main/exasol/bucketfs/_path.py#L228), [BucketLike](https://github.com/exasol/bucketfs-python/blob/main/exasol/bucketfs/_buckets.py#L38), and [PathLike](https://github.com/exasol/bucketfs-python/blob/main/exasol/bucketfs/_path.py#L21).

### Examples

ai-lab Notebooks [cloud_store_config.ipynb](https://github.com/exasol/ai-lab/blob/main/exasol/ds/sandbox/runtime/ansible/roles/jupyter/files/notebook/cloud/cloud_store_config.ipynb) and [sklearn_train_abalone.ipynb](https://github.com/exasol/ai-lab/blob/main/exasol/ds/sandbox/runtime/ansible/roles/jupyter/files/notebook/sklearn/sklearn_train_abalone.ipynb).

#### O1) Call BucketPath constructor, see example in [ai-lab/cloud_store_config.ipynb](https://github.com/exasol/ai-lab/blob/main/exasol/ds/sandbox/runtime/ansible/roles/jupyter/files/notebook/cloud/cloud_store_config.ipynb).

```python
local_name = jar_local_path.name
bfs_path = bfs.path.BucketPath(local_name, open_bucketfs_connection(ai_lab_config))
with jar_local_path.open("rb") as file:
    bfs_path.write(file)
udf_path = bfs_path.as_udf_path()
```

#### O2) Use BucketLike.upload(), see example in [ai-lab/sklearn_train_abalone.ipynb](https://github.com/exasol/ai-lab/blob/main/exasol/ds/sandbox/runtime/ansible/roles/jupyter/files/notebook/sklearn/sklearn_train_abalone.ipynb).

```python
local_name = jar_local_path.name
bfs = open_bucketfs_connection(ai_lab_config)
bfs.upload(local_name, jar_local_path)
udf_path = bfs.path.BucketPath(local_name, bfs).udf_path
```

#### I1) Add operator `/` to `BucketLike`

```python
bpath = open_bucketfs_connection(ai_lab_config) / jar.name
with jar.open("rb") as file:
    bpath.write(file)
udf_path = bpath.udf_path
```

#### I2) Add operator `/` to `BucketLike` and add `upload()` method to `BucketPath`

```python
bpath = open_bucketfs_connection(ai_lab_config) / jar.name
udf_path = bpath.upload(jar).udf_path
```

#### I3) Make `BucketLike.upload()` return a `BucketPath` object

```python
bfs = open_bucketfs_connection(ai_lab_config)
udf_path = bfs.upload(jar.name, jar).udf_path
```

**Comment by Nicoretti** [comment]
Imho `I2` definetly breaks the API (seperation of concern of the interface).
My initial gut feeling is `I3` to be the best solution in regard to the suggestions, still I am not sure if I understood the problem which needs to be addressed well enough.
