### ISSUE TITLE
🐞 Generating and deploying multi version documentation fails

### ISSUE THREAD

**Issue by Nicoretti** [exasol/bucketfs-python#36]
# Summary
Generating and deploying multi version documentation does not work properly in all scenarios and workflows.

## Reproducing the Issue

Scenario 1:
* Re-run a workflow which was run successfully for a push on master/main

Scenario 2:
* Run CI-CD workflow (triggered by tag push)

## Expected Behavior
Entire multi version documentation gets built and deployed to GitHub pages.

## Actual Behavior
Documentation build/workflow fails.

## Root Cause (optional)
No clear single root cause identified yet.

### Leads
There are two major issues which have been identified so far:

1. The docs build expects a setup/structure which causes a broken rendering of the API docs, otherwise it fails
    ```
    /tmp/tmpywesr85d/worktrees/worktree_source/doc/api.rst:4:toctree contains reference to nonexisting document 'api/exasol_bucketfs_utils_python'
    ```
2. The `sgpg` tool expects different parameters depending if a tag or branch is used as source, therefore the unparamerized
github workflow won't work properly in all cases.

#### Related Issues (optional)
* https://github.com/exasol/bucketfs-python/issues/2

**Comment by tkilias** [comment]
This bug is obsolete, because we are not using sgpg anymore.
