### ISSUE TITLE
User guide and Examples

### ISSUE THREAD

**Issue by exa-eswar** [exasol/bucketfs-python#37]
It would be beneficial for the users to have a User guide (like other Exasol public repos) along with a few working examples.

**Comment by Nicoretti** [comment]
@exa-eswar doesn't it have some basic user [guide]( https://exasol.github.io/bucketfs-python/user_guide/user_guide.html)?

**Comment by exa-eswar** [comment]
@Nicoretti, Yes this is sufficient. I was searching in Repo's readme file.
