### ISSUE TITLE
✨ Add extra features to new BucketFs API

### ISSUE THREAD

**Issue by Nicoretti** [exasol/bucketfs-python#42]
# Summary
Add missing extra features to new BucketFs API to match needs of UDF use cases

# Details

## Location / BucketFsLocation
Implement a location "type" which provides to ability to operate on a subpath within a bucket.
Ask @tkilias for more details.

## UDF path
Provide api to deduce the bucketfs path within a UDF.

# Task(s)
- [ ] Add Location support
- [ ] Add UDF path/url support

**Comment by Nicoretti** [comment]
Moved "CredentialsProvider" into it's own issue (see https://github.com/exasol/bucketfs-python/issues/75)

**Comment by tkilias** [comment]
Done in https://github.com/exasol/bucketfs-python/issues/114
