### ISSUE TITLE
Ability to create Bucket 

### ISSUE THREAD

**Issue by exa-eswar** [exasol/bucketfs-python#53]
In order to be able to integrate Exasol closely with ML pipelines, this feature would be highly helpful.

**Comment by Nicoretti** [comment]
@exa-eswar  isn't this more or less a duplicate of #18?

**Comment by exa-eswar** [comment]
@Nicoretti you are right. This is also addressing the same feature, which is ability to create Bucket via bucketfs-utils-python.

**Comment by Nicoretti** [comment]
Duplicate, see #18
