### ISSUE TITLE
Add DirectoryBucket (Pathlike, BucketPath, ...) to new API

### ISSUE THREAD

**Issue by tkilias** [exasol/bucketfs-python#68]
# Background

- The new API is object-oriented
- It uses objects like the Service, Bucket, MappedBucket
- A MappedBucket is in that sense an Adapter for a Bucket. This way we can use composition instead of inheritance for the implementation.
- However, Bucket and MappedBucket require the user to specify the path from the root
- For more complex usage scenarios where multiple components of an application need to store objects in the BucketFS, we want that they can do that independent of each other.
  - For example, each component could use its own subdirectory.  However, managing the absolute paths to subdirectories manually is error-prone.
- For that reason, we need a DirectoryBucket which gets a Bucket and a path to a subdirectory and writes and reads objects below the subdirectory 

# Acceptance Criteria

- [ ] Implement DirectoryBucket
  - [ ] read
  - [ ] write
  - [ ] delete
  - [ ] files
  - [ ] directories # return direct subdirectories as DirectoryBucket
  - [ ] join_path
- [ ] Implement unit tests
- [ ] Implement integration tests

**Comment by redcatbear** [comment]
Obsolete.
