### ISSUE TITLE
Wrong assumption of a path in a bucket always having subdirectories

### ISSUE THREAD

**Issue by ahsimb** [exasol/bucketfs-python#77]
## Summary

If a bucket url points to the bucket root then the line below fails
```python
            base_path_in_bucket = PurePosixPath(url_path.parts[2]).joinpath(
                *url_path.parts[3:]
            )
```
This is in the `BucketFSFactory.create_bucketfs_location` in `bucketfs_factory.py` at the time of writing in the line 45.
See [here](https://github.com/exasol/bucketfs-python/blob/d4275693d2c054e0f4006006c38ec1ee2aca360c/exasol_bucketfs_utils_python/bucketfs_factory.py#L45).

## Related Issues
* https://github.com/exasol/bucketfs-python/issues/42

**Comment by Nicoretti** [comment]
> This is in the BucketFSFactory.create_bucketfs_location in bucketfs_factory.py at the time of writing in the line 45.
Side note: @ahsimb GitHub supports adding permalinks to source code locations (I have added one).

**Comment by Nicoretti** [comment]
This is an issue of the legacy api, imho this should be addressed by implementing https://github.com/exasol/bucketfs-python/issues/42.

**Comment by tkilias** [comment]
With https://github.com/exasol/bucketfs-python/issues/114 we have subpath handling in the new API. In the next weeks, we will replace the usage of the old API in our projects. This makes the old API obsolete. For that reason, we won't fix this bug.
